### ISSUE TITLE
能否解释一下该项目和 redis-shake 的差异点？

### ISSUE THREAD

**Issue by cobolbaby** [mgtv-tech/redis-GunYu#1]

**Comment by ikenchina** [comment]
功能点 | redis-shake/v2 | redis-shake/v4 | DTS | xpipe | redis-GunYu
-- | -- | -- | -- | -- | --
断点续传 | Y(无本地缓存)  | N | Y | Y | Y
支持分片不对称 | N | N | Y | N | Y
拓扑变化 | N | N | N | N | Y
高可用 | N | N | N | Y | Y
数据一致性 | 最终 | 弱 | 弱 | 弱 | 最终(分片对称) + 弱(不对称)
