### ISSUE TITLE
请问大佬这个项目如何发音😁

### ISSUE THREAD

**Issue by alinuxsa** [mgtv-tech/redis-GunYu#38]
发现这个项目可以实现集群同步，打算使用，不知道如何发音给同事读这个项目名，求告知

**Comment by ikenchina** [comment]
鲧禹，你就说大禹吧，简单些。哈哈。
你们什么公司啊，可以告知下吗？
可以加微信群
![微信图片_20240701091432](https://github.com/mgtv-tech/redis-GunYu/assets/3422667/b2ba799e-8f2e-49d0-9da0-15fa67856a37)

**Comment by alinuxsa** [comment]
> 鲧禹，你就说大禹吧，简单些。哈哈。
> 
> 你们什么公司啊，可以告知下吗？
> 
> 可以加微信群
> 
> ![微信图片_20240701091432](https://github.com/mgtv-tech/redis-GunYu/assets/3422667/b2ba799e-8f2e-49d0-9da0-15fa67856a37)
> 
> 
> 
> 

感谢大佬拉群，小公司没啥名气，名不见经传哈哈😄

**Comment by lipengfei333** [comment]
大佬，群二维码能不能辛苦再发一下

**Comment by lday0321** [comment]
@ikenchina 二维码过期了， 能不能更新一个。

**Comment by lipengfei333** [comment]
您好，您发的邮件我已收到。

**Comment by lday0321** [comment]
@ikenchina 能再更新下吗？ 又错过二维码时效期了...

**Comment by lday0321** [comment]
@alinuxsa 能再更新下吗？ 又错过二维码时效期了...

**Comment by cmsshg** [comment]
> @alinuxsa 能再更新下吗？ 又错过二维码时效期了...

![image](https://github.com/user-attachments/assets/f8ec9a7d-f508-4eb3-8730-a2749cb3f8e1)
