### ISSUE TITLE
GunYu是否支持长时间的数据同步和双向同步

### ISSUE THREAD

**Issue by lipengfei333** [mgtv-tech/redis-GunYu#44]
您好，
咨询两个问题：
1. GunYu是否支持在生产环境进行长时间的数据同步，用于做双中心redis集群数据灾备
2. 是否支持双向同步，A、B两个redis集群间启动一个或者两个GunYu实例，进行双向同步，这样就能支持双活了

**Comment by ikenchina** [comment]
1. 支持的，有一些公司已经在生产环境这么用
2. 不支持双向同步哈，不是这一个工具能解决的了。

**Comment by lipengfei333** [comment]
您好，您发的邮件我已收到。

**Comment by lipengfei333** [comment]
多谢解答
