### ISSUE TITLE
工具支持自动的主从切换吗？

### ISSUE THREAD

**Issue by devin1982** [mgtv-tech/redis-GunYu#45]
比如a集群是一个sentinel集群，redis-gunyu开始连接在master库同步，集群发生了主从切换，redis-gunyu能自动切换同步地址吗？

**Comment by ikenchina** [comment]
看怎么配置，如果input.syncFrom配置的是prefer_slave，则不会切换，如果是slave，则会切换。
[参考配置文档](https://github.com/mgtv-tech/redis-GunYu/blob/master/docs/configuration_zh.md#%E8%BE%93%E5%85%A5%E7%AB%AF)
