### ISSUE TITLE
关于GLIBC版本问题

### ISSUE THREAD

**Issue by lipengfei333** [mgtv-tech/redis-GunYu#47]
请问GunYu 对glibc版本有要求吗？我使用预编译的0.1.8测试时，运行报错，提示GLIBC_2.32 GLIBC_2.34 not found，
必须安装到GLIBC_2.32以上才可以吗？
![Uploading WX20240717-220818@2x.png…]()

**Comment by lipengfei333** [comment]
![WechatIMG1442](https://github.com/user-attachments/assets/3113e8e0-1cc1-48e5-b1ef-d3ab0226217e)

**Comment by lipengfei333** [comment]
我本地glic版本为2.28

**Comment by ikenchina** [comment]
没有关系的，是你编译的机器和运行的机器版本兼容问题。

**Comment by lipengfei333** [comment]
我使用的是从git下载的编译后的，直接在测试环境运行，就提示glibc版本不兼容。那是不是不能直接从git下载编译好的，得在自己的测试环境重新编译了？
