### ISSUE TITLE
请问func (rr *RdbReplay) Replay(e *rdb.BinEntry)中一段代码实现目的

### ISSUE THREAD

**Issue by steedyu** [mgtv-tech/redis-GunYu#57]
阅读了上述源码，有几个地方疑问，想请教一下

这里restoreCmd  默认是true。e.CanRestore()理解的化，应该是回放命令是否支持restore，一般都是支持的
e.ObjectParser.ValueDumpSize() > rr.MaxProtoBulkLen  这句判断的目的是什么？
_restoreCmd := rr.EnableRestore
	if restoreCmd &&
		(!e.CanRestore() || e.ObjectParser.ValueDumpSize() > rr.MaxProtoBulkLen ||
			e.ObjectParser.IsSplited()) {
		restoreCmd = false
	}_

	if !restoreCmd {
		if e.FirstBin() {
			exist, err := common.Bool(rr.Client.Do("exists", e.Key))
			if err != nil {
				return err
			}
			if exist {
				switch rr.KeyExists {
				case "replace":
					if rr.KeyExistsLog {
						log.Infof("replace key: %s", e.Key)
					}
					_, err := common.Int64(rr.Client.Do("del", e.Key))
					if err != nil {
						return fmt.Errorf("del exist key error : key(%s), error(%w)", e.Key, err)
					}
				case "ignore":
					if rr.KeyExistsLog {
						log.Warnf("output key exist, ignore it : %s", e.Key)
					}
				case "error":
					return fmt.Errorf("output key exist : %s", e.Key)
				}
			}
		}

		err = restoreBigRdbEntry(rr.Client, e)
		if err != nil {
			return err
		}
		if e.ExpireAt != 0 {
			r, err := common.Int64(rr.Client.Do("pexpire", e.Key, ttlms))
			if err != nil && r != 1 {
				return fmt.Errorf("expire key error : key(%s), error(%w)", e.Key, err)
			}
		}
		return nil
	}

	params := []interface{}{e.Key, ttlms, e.DumpValue()}
	if util.VersionGE(rr.RedisVersion, "5", util.VersionMajor) {
		if e.IdleTime != 0 {
			params = append(params, "IDLETIME")
			params = append(params, e.IdleTime)
		}
		if e.Freq != 0 {
			params = append(params, "FREQ")
			params = append(params, e.Freq)
		}
	}
RESTORE:
	s, err := common.String(rr.Client.Do("restore", params...))

这里失败restore如果失败，则会增加replace，让命令再次执行，则会替换掉原来已存在key的内容，这个的目的是完全相信元数据的操作吧

	if err != nil {
		/*The reply value of busykey in 2.8 kernel is "target key name is busy",
		  but in 4.0 kernel is "BUSYKEY Target key name already exists"*/
		if strings.Contains(err.Error(), "Target key name is busy") ||
			strings.Contains(err.Error(), "BUSYKEY Target key name already exists") {
			switch rr.KeyExists {
			_case "replace":
				if rr.KeyExistsLog {
					log.Infof("replace key: %s", e.Key)
				}
				params = append(params, "REPLACE")
				goto RESTORE_
			case "ignore":
				if rr.KeyExistsLog {
					log.Warnf("output key exist, ignore it : %s", e.Key)
				}
			case "error":
				return fmt.Errorf("output key exist, none : %s", e.Key)
			}
		} else if strings.Contains(err.Error(), "Bad data format") { // cluster.c:restoreCommand
			log.Warn(err, " try to restoreBigRdbEntry")
			if err := restoreBigRdbEntry(rr.Client, e); err != nil {
				return err
			}
		} else {
			return fmt.Errorf("restore command error : key(%s), error(%w)", e.Key, err)
		}
	} else if s != "OK" {
		return fmt.Errorf("restore command response is not OK : %s", s)
	}

**Comment by ikenchina** [comment]
e.ObjectParser.ValueDumpSize() > rr.MaxProtoBulkLen  :  是判断dump的数据大小如果超过redis 服务端设置的最大proto size，则要改成非restore方式。
replace就是完全替换掉，因为要考虑源同步偏移不在源redis buffer里，就会启动rdb，这样会导致busy
