### ISSUE TITLE
input配置syncFrom: prefer_slave 问题。

### ISSUE THREAD

**Issue by erwadba** [mgtv-tech/redis-GunYu#61]
环境：配置了2个redisGunYu。从redis-cluster-A同步到redis-cluster-B
配置文件中都配置prefer_slave。如果源端slave宕机。redisGunYu能正常漂移到master继续同步。slave恢复正常后。此时，重启没有同步master节点的redisGunYu，会出现该master和slave同时向目标端同步的问题。

**Comment by ikenchina** [comment]
v0.1.3已经修复了，https://github.com/mgtv-tech/redis-GunYu/releases/tag/v1.0.3
