### ISSUE TITLE
异常求助：重启GunYu报错，run error: redis: invalid reply : "\n"

### ISSUE THREAD

**Issue by lipengfei333** [mgtv-tech/redis-GunYu#73]
![WechatIMG399](https://github.com/user-attachments/assets/cc62ed35-001f-4029-b456-40cea7777a81)
之前GunYu服务正常运行，重启后报错，能帮忙定位下吗？

**Comment by ikenchina** [comment]
也许是buffer不够。可以调大一些，如下示例：
config set client-output-buffer-limit "normal 0 0 0 slave 5073741824 2073435456 120 pubsub 33554432 8388608 60"

**Comment by lipengfei333** [comment]
您好，您发的邮件我已收到。
