### ISSUE TITLE
redis主从vip发生漂移后，syncDelayTestKey存在问题

### ISSUE THREAD

**Issue by sun642514265** [mgtv-tech/redis-GunYu#78]
架构：1主1从，通过sentinel + VIP 实现高可用。 redis-GunYun通过 vip 连接源端redis。 GunYun配置了syncDelayTestKey: redis-GunYu-syncDelay-testKey  

问题：
1、当redis主从发生切换后，vip从A节点漂移到了B节点。redis的增量同步恢复正常，但是日志一直输出以下信息：
2024-11-19 08:17:44	warn	syncer/input.go:494	[RedisInput(192.168.2.20:6891)] checkSyncDelay, set testkey : addr(192.168.2.20:6891), error(write tcp 172.17.0.4:41140->192.168.2.20:6891: write: brokenpipe)

感觉像是：当vip发生漂移时， GunYun连接源端redis的vip连接没有释放（tcp层的问题）。是否可以调整成，当出现此问题时，先重试几秒，如果不行，在断掉已有链接，重新创建新链接。

![image](https://github.com/user-attachments/assets/41b5995f-d7c8-4506-a38b-9f7383785631)

**Comment by sun642514265** [comment]
当vip 从A节点漂移到B节点后，此时没有问题。紧接着，vip 从B节点再漂移到A节点后，就会出现此现象。

**Comment by ikenchina** [comment]
已修复，合并到master分支，可以自己编译哈

**Comment by ikenchina** [comment]
![mmqrcode1732075113760](https://github.com/user-attachments/assets/84f6149e-2604-4940-840b-425d4c9c443a)
可以加微信群

**Comment by sun642514265** [comment]
> 已修复，合并到master分支，可以自己编译哈

测试发现有新的问题：

当主从发生切换后，vip 从A节点漂移到B节点，GunYun的 leader节点居然挂掉了。挂掉的日志如下：
![image](https://github.com/user-attachments/assets/9ea40ace-ab8f-421f-aff0-bf976809ec80)

**Comment by sun642514265** [comment]
@ikenchina 大佬，有时间 看下上面的问题啊。刚采用您修改后的测试了下，有新的问题了。

**Comment by sun642514265** [comment]
@ikenchina 大佬，还发现个现象，当redis主从发生切换时，vip从A节点漂移到B节点，此时GunYun主备服务也做了切换（leader 变成了follower），这个现象正常吗？

**Comment by ikenchina** [comment]
这个是有可能的，长时间连接不到redis，会自动换
