### ISSUE TITLE
跨数据中心（北京-成都，网络延迟60ms）同步，同步性能低。

### ISSUE THREAD

**Issue by sun642514265** [mgtv-tech/redis-GunYu#80]
大佬，我将数据 从北京同步到成都，同步性能上不去，有什么优化办法吗?  两地网络延迟60ms左右。参数文件如下：

server:
  listen: 0.0.0.0:18001
  listenPeer: 192.168.x.x:18001
input:
  redis:
    addresses: [192.168.x.x:6389]
    password: "xxx"
    type: standalone
  mode: static
  syncFrom: master
  syncDelayTestKey: redis-GunYu-syncDelay-testKey
channel:
  storer:
    dirPath: /data/redisGunYu/data/xxx
    maxSize: 53687091200
    logSize: 104857600
    flush: auto
  staleCheckpointDuration: 12h
output:
  redis:
    addresses: [192.168.x.x:6389]
    password: "xxx"
    type: standalone
  filter:
    resumeFromBreakPoint: true
log:
  level: info
  handler:
    stdout: false
    file:
      fileName: /data/redisGunYu/logs/xxx.log
      maxSize: 100
      maxAge: 14
  withModuleName: true

cluster:
  groupName: xxx
  leaseTimeout: 5s
  metaEtcd:
    username: root
    password: xxx
    endpoints:
      - 192.168.x.x:2379
      - 192.168.x.x:2379
      - 192.168.x.x:2379

**Comment by ikenchina** [comment]
replayTransaction=false和enableAofPipeline=true试试，
