### ISSUE TITLE
可以支持實時一直同步嗎?

### ISSUE THREAD

**Issue by lewis100challenges** [mgtv-tech/redis-GunYu#83]
你好作者，想詢問一下，
我兩地機房，距離比較遠，本來是用redis自己的master和slave的方式去同步，偶爾會有斷線狀況發生，
斷線後，數據差，變的要全同步，全同步又非常耗時，
我有開啟redis的buffer，讓他緩存多一點，好讓他短暫斷後恢復後，盡量不要做全同步，
但偶爾還是會有斷線，還是會全同步發生，導致遠地機房會有數據差，
所以我希望可以靠著建立另外一個高可用的工具，保持兩邊一直實實同步資料，也就是，源master -> 外部工具 -> 目的master
此工具，是可以做到嗎? 感謝您看完，謝謝。

**Comment by ikenchina** [comment]
支持的，从源redis同步数据到工具，工具再写入到目的redis。看看文档吧。
