### ISSUE TITLE
詢問一下，channel、log的maxSize、logSize是如何計算?

### ISSUE THREAD

**Issue by lewis100challenges** [mgtv-tech/redis-GunYu#84]
您好作者，我測試了，確實可以實時同步沒問題，感謝您的貢獻!!

我有以下計算的問題，我看文件還是有不太懂的地方，您寫channel那裏的maxSize預設是50G，如果滿了，會發生什麼狀況嗎?

如果以以下兩個地方的maxSize、logSize為範例，那他到底會是多少容量，我想再次與您確認一下，感謝您的查看與回覆!!

channel:
  storer:
    dirPath: /tmp/redisgunyu-cluster
    maxSize: 209715200
    logSize: 20971520

log:
  level: info
  handler:
    file:
      fileName: /tmp/redisgunyu-cluster/log/stdout.log
      maxSize: 2048
      maxBackups: 7
      maxAge: 7

**Comment by ikenchina** [comment]
maxSize是本地缓存最大的容量限制，不用太大，如果缓存超过此容量，则会触发回收，回收最老的日志。
logSize是一个缓存文件的大小。
例如，maxSize: 21474836480, 是20GB的最大缓存容量，
logSize: 209715200, 每个缓存文件大小是200MB。
